In [29]:
#Vectorization based Linear Regression

In [1]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
#only for jupyter notebook
%matplotlib inline 

In [2]:
dataSet = 'data.xlsx'

In [3]:
#header = None states that there is no header row or else it would take first row of our data as header.
df = pd.read_excel(dataSet,sheet_name='Sheet1',header=None)

In [4]:
valueArray = df.to_numpy() #dataframe DF to numpyarray valueArray
m = valueArray.shape[0] # Number of training examples   numpyArray.shape = (no of rows,no of cols)
X = valueArray[0:,0:2] # Feature Vector [x1,x2] m*2 0: = 0,1,2 rows and 0:2 = 0,1 columns
X = np.insert(X,0,1,axis=1) # axis = 1 (every row insert 1 at 0 column) , Adding x0 = 1 in feature matrix m*3
y = valueArray[0:,2:] # Class label Vector [y]  0: = 0,1,2 rows and 2: = 2 column   y = m*1 matrix

In [5]:
#Normalization
X[0:,1:2] = (X[0:,1:2] - X[0:,1:2].mean())/(X[0:,1:2].std())
X[0:,2:] = (X[0:,2:] - X[0:,2:].mean())/(X[0:,2:].std())

In [10]:
np.matmul(X.transpose(),X).shape

(3, 3)

In [35]:
# w = (X^T X)^-1 X^T Y
w = np.matmul(np.matmul(np.linalg.inv(np.matmul(X.transpose(),X)),X.transpose()),y)

In [36]:
print(w)

[[14.90479943]
 [ 0.36737803]
 [ 1.69668329]]


In [37]:
# [14.89086773 0.37009743 1.69375798] #batch gradient descent
# [14.96050473 0.30193768 1.8204537] #stochastic gradient descent
# [14.90479943 0.36737803 1.69668329] #vectorization